# Generated by Django 5.0.14 on 2026-01-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('GBP', 'GBP - British Pound'), ('AED', 'AED - UAE Dirham'), ('SAR', 'SAR - Saudi Riyal'), ('PKR', 'PKR - Pakistani Rupee')], default='USD', max_length=8),
        ),
    ]
