# Generated by Django 5.0.14 on 2026-01-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
    ]
