# Generated by Django 5.0.14 on 2026-01-29 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_service_category'),
        ('clients', '0002_client_notes_client_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vapi_call_id', models.CharField(blank=True, db_index=True, help_text='Vapi call/assistant call id for idempotency.', max_length=255)),
                ('caller_name', models.CharField(blank=True, max_length=255)),
                ('caller_number', models.CharField(blank=True, max_length=50)),
                ('service_name', models.CharField(blank=True, help_text='Service discussed or booked (e.g. Haircut, Cleansing).', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=8)),
                ('summary', models.TextField(blank=True, help_text='AI-generated call summary.')),
                ('transcript', models.TextField(blank=True, help_text='Full or partial call transcript.')),
                ('outcome', models.CharField(blank=True, help_text='e.g. Booking created, Rescheduled, Lead captured.', max_length=64)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_summaries', to=settings.AUTH_USER_MODEL)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_summaries', to='bookings.booking')),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_summaries', to='clients.client')),
            ],
            options={
                'verbose_name_plural': 'Call summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
